version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ~/Documents/Repositorys/shared-todo-list/client:/app
    depends_on:
      - server
  
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ~/Documents/Repositorys/shared-todo-list/server:/app
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - ~/Documents/Repositorys/shared-todo-list/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql