version: "3.8"

services:
  mysql:
    container_name: todo-mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./shared-todo-list/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  server:
    container_name: todo_server
    build:
      context: ./server/
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./shared-todo-list/server:/app
    depends_on:
      mysql:
        condition: service_healthy
  
  client:
    container_name: todo_client
    build: 
      context: ./client/
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./shared-todo-list/client:/app
    depends_on:
      - server